---

name: Build and test a PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Extract dependent PR
        uses: leseb/depends-on-action@feat-rust
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build and test
        run: |
          cargo run

  check-all-dependencies-are-merged:
    runs-on: ubuntu-latest
    steps:

      - name: Extract dependent PR
        uses: leseb/depends-on-action@feat-rust
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true

...
