---
name: Rust

on:
  push:
    branches: [ "main", "first" ]
  pull_request:
    branches: [ "main", "first" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract dependent PR
      uses: leseb/depends-on-action@feat-rust
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run program
      run: cargo run --verbose

  check-all-dependencies-are-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Extract dependent PR
        uses: leseb/depends-on-action@feat-rust
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true
